### ISSUE TITLE
URL from packet website is pointing to wrong address?

### ISSUE THREAD

**Issue by eneim** [packethost/packet-java#1]
I believe at the time of 2017/01/13, this site [https://www.packet.net/developers/integrations/java-client/](https://www.packet.net/developers/integrations/java-client/) point to python client instead. Please double check it.

**Comment by zloster** [comment]
I'm confirming the above observation.

**Comment by jacobsmith928** [comment]
Thanks all - I've redirected the url in question, which is now the top level URL for all integrations.
